version: "3.9"
services:

  kaddem:
    container_name: kaddem
    image: kaddem
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "8089:8089"
    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3308/kaddem\db?&createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      spring.jpa.hibernate.ddl-auto : update
      spring.jpa.properties.hibernate.dialect : org.hibernate.dialect.MySQL5Dialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.cj.jdbc.Driver
    depends_on:
      - mysqldb
    volumes:
      - .m2:/root/.m2
    networks:
      - my-network


  mysqldb:
    image: "mysql:5.6"
    container_name: mysql-container
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=kaddem
    ports:
      - "3308:3306"
    restart: unless-stopped
    volumes:
      - db:/var/lib/mysql
    networks:
      - my-network

  angular-app:
    image: ounimohamed/kaddem-front
    container_name: angular-app
    ports:
      - "4200:80"
    depends_on:
      - kaddem
    networks:
      - my-network


volumes:
  db :
networks:
  my-network:

